name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v30
      - run: nix develop --command bash -c "./bin/download-compiler && gleam deps download && gleam format --check src test && gleam test && gleam run"
